apiVersion: v1
kind: Service
name: my-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-service
labels:
  version: b
  app: my-service