# Profile containing Istio enricher
# The istio-default profile is defined in the Istio enricher but is overridden here
# we need to remove the fmp-project enricher that messes up labels and selectors
- name: default
  enricher:
    excludes:
    - fmp-project